from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.analysis_outputs import ComparisonMetric, GeneratedAsset, Recommendation
from app.models.analysis_run import AnalysisRun
from app.models.competitor import Competitor
from app.models.enums import AnalysisGoal, AssetType, RunStatus
from app.models.project import Project


class RunService:
    def __init__(self, db: Session):
        self.db = db

    def start_run(self, project: Project, goal: AnalysisGoal) -> AnalysisRun:
        run = AnalysisRun(project_id=project.id, goal=goal, status=RunStatus.PENDING, current_stage="queued")
        self.db.add(run)
        self.db.commit()
        self.db.refresh(run)
        return run

    def get_run(self, run_id: int) -> AnalysisRun | None:
        return self.db.get(AnalysisRun, run_id)

    def set_stage(self, run_id: int, stage: str, status: RunStatus = RunStatus.RUNNING) -> None:
        run = self.get_run(run_id)
        if run is None:
            return
        run.current_stage = stage
        run.status = status
        self.db.commit()

    def finalize_with_mock_data(self, run_id: int) -> None:
        run = self.get_run(run_id)
        if run is None:
            return

        # TODO: replace with real comparison/recommendation generation.
        self.db.add_all(
            [
                Competitor(run_id=run_id, domain="example-competitor.com", reason="High SERP overlap"),
                Competitor(run_id=run_id, domain="another-rival.io", reason="Strong local visibility"),
                ComparisonMetric(
                    run_id=run_id,
                    metric_name="Content Depth",
                    your_value="Low",
                    competitor_avg="High",
                    delta="-2",
                ),
                Recommendation(
                    run_id=run_id,
                    title="Create geo-specific service pages",
                    detail="Add pages optimized for priority regions and services.",
                    priority="high",
                ),
                GeneratedAsset(
                    run_id=run_id,
                    asset_type=AssetType.LANDING_PAGE,
                    title="Draft landing page",
                    content="[MOCK] Landing page draft generated by scaffold.",
                ),
            ]
        )
        run.status = RunStatus.COMPLETED
        run.current_stage = "done"
        self.db.commit()

    def list_competitors(self, run_id: int) -> list[Competitor]:
        return list(self.db.scalars(select(Competitor).where(Competitor.run_id == run_id)).all())

    def list_comparison(self, run_id: int) -> list[ComparisonMetric]:
        return list(self.db.scalars(select(ComparisonMetric).where(ComparisonMetric.run_id == run_id)).all())

    def list_recommendations(self, run_id: int) -> list[Recommendation]:
        return list(self.db.scalars(select(Recommendation).where(Recommendation.run_id == run_id)).all())

    def list_assets(self, run_id: int, asset_type: AssetType) -> list[GeneratedAsset]:
        stmt = select(GeneratedAsset).where(GeneratedAsset.run_id == run_id, GeneratedAsset.asset_type == asset_type)
        return list(self.db.scalars(stmt).all())
